Repository VRGuild/Backend, pull requests merged in 2024-11, with the labels that each got.

#83 [DS-refactor-table-and-api] refactor: Domain:Character API 구현
  src/main/java/com/mtvs/devlinkbackend/character/controller/UserCharacterCommandController.java
  src/main/java/com/mtvs/devlinkbackend/character/controller/UserCharacterQueryController.java
  src/main/java/com/mtvs/devlinkbackend/character/dto/request/UserCharacterRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/dto/request/UserCharacterUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/dto/response/UserCharacterListResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/entity/CustomInfo.java
  src/main/java/com/mtvs/devlinkbackend/character/entity/UserCharacter.java
  src/main/java/com/mtvs/devlinkbackend/character/repository/UserCharacterRepository.java
  src/main/java/com/mtvs/devlinkbackend/character/repository/UserCharacterViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/character/service/UserCharacterService.java
  src/main/java/com/mtvs/devlinkbackend/character/service/UserCharacterViewService.java
  src/main/java/com/mtvs/devlinkbackend/user/command/model/entity/Dev.java
  src/main/java/com/mtvs/devlinkbackend/user/command/model/entity/User.java
  src/main/java/com/mtvs/devlinkbackend/user/query/repository/UserViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/util/converter/IntegerListConverter.java
  src/main/java/com/mtvs/devlinkbackend/util/converter/LongListConverter.java
  src/main/java/com/mtvs/devlinkbackend/util/converter/StringListConverter.java
  src/test/java/com/mtvs/devlinkbackend/crud/BusinessCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/DevCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/UserCharacterCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/UserClientIndividualCRUDTest.java
Labels: ✨Feature

#87 [PL-member-crud] 멤버 CRUD API 구현 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/member/command/controller/MemberCommandController.java
  src/main/java/com/mtvs/devlinkbackend/member/command/model/entity/AcceptStatus.java
  src/main/java/com/mtvs/devlinkbackend/member/command/model/entity/Member.java
  src/main/java/com/mtvs/devlinkbackend/member/command/repository/MemberRepository.java
  src/main/java/com/mtvs/devlinkbackend/member/command/service/MemberService.java
  src/main/java/com/mtvs/devlinkbackend/member/query/controller/MemberQueryController.java
  src/main/java/com/mtvs/devlinkbackend/member/query/repository/MemberViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/member/query/service/MemberViewService.java
  src/main/java/com/mtvs/devlinkbackend/member/query/view/response/MemberStatusResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/member/service/MemberService.java
  src/main/java/com/mtvs/devlinkbackend/member/service/MemberViewService.java
  src/main/java/com/mtvs/devlinkbackend/team/dto/request/TeamMemberModifyRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/team/dto/request/TeamUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/team/service/TeamService.java
  src/main/java/com/mtvs/devlinkbackend/user/command/service/EpicDevService.java
  src/main/java/com/mtvs/devlinkbackend/user/query/service/EpicGamesTokenService.java
  src/main/java/com/mtvs/devlinkbackend/util/converter/AcceptStatusConverter.java
  src/test/java/com/mtvs/devlinkbackend/crud/MemberCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/TeamCRUDTest.java
Labels: ✨Feature, ✅ Test

#91 refactor: 기존의 정해지지 않은 컬럼 CharacterPicture에 대한 타입 구체화
  src/main/java/com/mtvs/devlinkbackend/character/dto/request/UserCharacterRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/dto/request/UserCharacterUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/entity/CharacterPicture.java
  src/main/java/com/mtvs/devlinkbackend/character/entity/UserCharacter.java
Labels: ✨Feature

#92 refactor: 추가적으로 댓글 세부 조회 API 구현
  src/main/java/com/mtvs/devlinkbackend/comment/controller/CommentQueryController.java
  src/main/java/com/mtvs/devlinkbackend/comment/dto/response/CommentDetailSingleResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/comment/dto/response/sub/CommentDetailDTO.java
  src/main/java/com/mtvs/devlinkbackend/comment/service/CommentViewService.java
  src/main/java/com/mtvs/devlinkbackend/user/command/model/entity/User.java
Labels: ✨Feature

#97 [PL-experience-crud] Experience 도메인 CRUD API 구현 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/common/util/converter/StringListConverter.java
  src/main/java/com/mtvs/devlinkbackend/experience/command/controller/ExperienceCommandController.java
  src/main/java/com/mtvs/devlinkbackend/experience/command/model/dto/request/ExperienceRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/experience/command/model/dto/request/ExperienceUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/experience/command/model/entity/Experience.java
  src/main/java/com/mtvs/devlinkbackend/experience/command/repository/ExperienceRepository.java
  src/main/java/com/mtvs/devlinkbackend/experience/command/service/ExperienceService.java
  src/main/java/com/mtvs/devlinkbackend/experience/query/controller/ExperienceQueryController.java
  src/main/java/com/mtvs/devlinkbackend/experience/query/model/dto/response/ExperienceListResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/experience/query/model/dto/response/ExperienceSingleResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/experience/query/repository/ExperienceViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/experience/query/service/ExperienceViewService.java
  src/main/java/com/mtvs/devlinkbackend/user/command/model/entity/Dev.java
  src/main/java/com/mtvs/devlinkbackend/user/command/repository/UserRepository.java
  src/test/java/com/mtvs/devlinkbackend/crud/ExperienceCRUDTest.java
Labels: ✨Feature, ✅ Test

#99 [DS-refactor-entity-and-api] Ether 도메인 API 리팩토링 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/ether/controller/EtherCommandController.java
  src/main/java/com/mtvs/devlinkbackend/ether/controller/EtherController.java
  src/main/java/com/mtvs/devlinkbackend/ether/controller/EtherQueryController.java
  src/main/java/com/mtvs/devlinkbackend/ether/dto/request/EtherUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/ether/dto/response/EtherPagingResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/ether/dto/response/UserEtherAmountResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/ether/dto/response/sub/UserIdAndAmountDTO.java
  src/main/java/com/mtvs/devlinkbackend/ether/entity/Ether.java
  src/main/java/com/mtvs/devlinkbackend/ether/repository/EtherRepository.java
  src/main/java/com/mtvs/devlinkbackend/ether/repository/EtherViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/ether/repository/projection/EtherGoldAndSilver.java
  src/main/java/com/mtvs/devlinkbackend/ether/service/EtherService.java
  src/main/java/com/mtvs/devlinkbackend/ether/service/EtherViewService.java
  src/main/java/com/mtvs/devlinkbackend/guild/controller/GuildQueryController.java
  src/main/java/com/mtvs/devlinkbackend/guild/dto/response/GuildDetailPagingResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/guild/service/GuildViewService.java
  src/main/java/com/mtvs/devlinkbackend/support/entity/Support.java
  src/main/java/com/mtvs/devlinkbackend/support/service/SupportService.java
  src/main/java/com/mtvs/devlinkbackend/user/command/controller/EpicDevCommandController.java
  src/test/java/com/mtvs/devlinkbackend/crud/EtherCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/SupportCRUDTest.java
Labels: 🔨 Refactor, ✅ Test

#100 fix: Channel 도메인 저장시 createdAt이 저장 안되는 문제 해결
  src/main/java/com/mtvs/devlinkbackend/channel/entity/Channel.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/ChannelService.java
Labels: 🐞Fix

#102 [PL-evaluation-crud] Evaluation 도메인 CRUD API 구현 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/character/controller/UserCharacterCommandController.java
  src/main/java/com/mtvs/devlinkbackend/character/dto/request/UserCharacterRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/dto/request/UserCharacterUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/entity/CharacterPicture.java
  src/main/java/com/mtvs/devlinkbackend/character/entity/UserCharacter.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/controller/EvaluationCommandController.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/dto/request/EvaluationRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/dto/request/EvaluationUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/dto/response/EvaluationListReponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/dto/response/EvaluationSingleResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/service/EvaluationService.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/domain/model/entity/Evaluation.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/domain/repository/EvaluationRepository.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/query/controller/EvaluationQueryController.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/query/repository/EvaluationViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/query/service/EvaluationViewService.java
  src/main/java/com/mtvs/devlinkbackend/user/command/model/entity/SkillCategoryInfo.java
  src/main/java/com/mtvs/devlinkbackend/user/query/model/dto/response/sub/CharacterInfoDTO.java
  src/main/java/com/mtvs/devlinkbackend/user/query/service/SkillCategoryViewService.java
  src/test/java/com/mtvs/devlinkbackend/crud/EvaluationCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/UserCharacterCRUDTest.java
Labels: ✨Feature, ✅ Test

#103 refactor: swagger에서 formdata로 보내는 로직 가능하게 수정
  src/main/java/com/mtvs/devlinkbackend/common/util/converter/LongListConverter.java
  src/main/java/com/mtvs/devlinkbackend/file/TestFileController.java
  src/main/java/com/mtvs/devlinkbackend/user/command/controller/EpicBusinessCommandController.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#107 DS-refactor-evaluation 수정
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/controller/EvaluationCommandController.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/dto/request/EvaluationUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/service/EvaluationService.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/domain/model/entity/Evaluation.java
  src/test/java/com/mtvs/devlinkbackend/crud/EvaluationCRUDTest.java
Labels: 🔨 Refactor

#112 refactor: All Dev Pagination GET Api의 ResponseDTO에 Nickname 추가
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectQueryController.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/response/ProjectCommnetResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/response/sub/ProjectIdAndCommnetIdListDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectSummaryViewService.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectViewService.java
  src/main/java/com/mtvs/devlinkbackend/user/query/model/dto/response/DevPagingResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/user/query/model/dto/response/sub/NicknameAndDevInfoDTO.java
  src/main/java/com/mtvs/devlinkbackend/user/query/service/EpicDevViewService.java
Labels: 🔨 Refactor

#114 feat: userCharacter Id 값 User에 넣기
  src/main/java/com/mtvs/devlinkbackend/character/service/UserCharacterService.java
  src/main/java/com/mtvs/devlinkbackend/character/service/UserCharacterViewService.java
Labels: 🔨 Refactor

#117 refactor: evaluation entity 컬럼 수정
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/controller/EvaluationCommandController.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/dto/request/EvaluationUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/application/service/EvaluationService.java
  src/main/java/com/mtvs/devlinkbackend/evaluation/command/domain/model/entity/Evaluation.java
Labels: 🔨 Refactor

#121 refactor: member 숫자로 내보내기 수정
  src/main/java/com/mtvs/devlinkbackend/guild/service/GuildService.java
  src/main/java/com/mtvs/devlinkbackend/guild/service/GuildViewService.java
  src/main/java/com/mtvs/devlinkbackend/member/command/service/MemberService.java
  src/main/java/com/mtvs/devlinkbackend/member/query/controller/MemberQueryController.java
  src/main/java/com/mtvs/devlinkbackend/member/query/service/MemberViewService.java
  src/main/java/com/mtvs/devlinkbackend/member/query/view/response/MemberStatusResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/member/query/view/response/sub/MemberDTO.java
  src/test/java/com/mtvs/devlinkbackend/crud/MemberCRUDTest.java
Labels: 🔨 Refactor

#122 fix: 멤버 수락 오류 수정
  src/main/java/com/mtvs/devlinkbackend/member/command/controller/MemberCommandController.java
Labels: 🐞Fix

#123 fix: 비즈니스 로직 수정
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectCommandController.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectService.java
Labels: 🔨 Refactor

#126 [DS-refactor-channel-entity] Channel 도메인 내용 변경으로 인한 기존 Service, Controller 로직 삭제와 Entity 수정
  src/main/java/com/mtvs/devlinkbackend/channel/controller/ChannelController.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/request/ChannelRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/request/ChannelUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/entity/Channel.java
  src/main/java/com/mtvs/devlinkbackend/channel/entity/PositionType.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/ChannelService.java
  src/test/java/com/mtvs/devlinkbackend/crud/ChannelCRUDTest.java
Labels: 🔨 Refactor

#131 [DS-tile-info-entity] Channel 도메인 TileInfo CRD Service로직 생성 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/channel/dto/request/ChannelUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/request/TileInfoRegistDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/response/TileInfoListResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/entity/Channel.java
  src/main/java/com/mtvs/devlinkbackend/channel/entity/Position.java
  src/main/java/com/mtvs/devlinkbackend/channel/entity/TileInfo.java
  src/main/java/com/mtvs/devlinkbackend/channel/repository/TileInfoRepository.java
  src/main/java/com/mtvs/devlinkbackend/channel/repository/TileInfoViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/TileInfoService.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/TileInfoViewService.java
  src/test/java/com/mtvs/devlinkbackend/crud/EvaluationCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/GuildCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/MemberCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/ProjectCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/TileInfoCRDTest.java
Labels: ✨Feature, ✅ Test

#134 [DS-object-info-entity] ObjectInfo 도메인 CRUD API 생성 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/channel/controller/ObjectInfoController.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/request/ObjectInfoRegistDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/response/ObjectInfoListResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/response/ObjectInfoSingleResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/entity/ObjectInfo.java
  src/main/java/com/mtvs/devlinkbackend/channel/repository/ObjectInfoRepository.java
  src/main/java/com/mtvs/devlinkbackend/channel/repository/ObjectInfoViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/ObjectInfoService.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/ObjectInfoViewService.java
  src/test/java/com/mtvs/devlinkbackend/crud/ObjectInfoCRUDTest.java
Labels: ✨Feature, ✅ Test

#135 [DS-tile-info-entity] TileInfo CRUD API 생성
  src/main/java/com/mtvs/devlinkbackend/channel/controller/TileInfoController.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/TileInfoService.java
  src/test/java/com/mtvs/devlinkbackend/crud/TileInfoCRDTest.java
Labels: ✨Feature, ✅ Test

#136 [DS-refactor-evaluation-sending] 평가 완료되지 않은 Dev들만 보내는 로직으로 변경
  src/main/java/com/mtvs/devlinkbackend/user/query/controller/EpicDevQueryController.java
  src/main/java/com/mtvs/devlinkbackend/user/query/repository/DevViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/user/query/service/EpicDevViewService.java
Labels: 🔨 Refactor

#137 [DS-add-all-channel] 전체 채널 페이징 조회 API 구현
  src/main/java/com/mtvs/devlinkbackend/channel/controller/ChannelController.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/response/ChannelListResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/repository/ChannelViewRepository.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/ChannelViewService.java
Labels: ✨Feature, ✅ Test
