Repository VRGuild/Backend, pull requests merged in 2024-10, with the labels that each got.

#31 [PL-config-swagger] Swagger API 명세서 설정 구현
  build.gradle
  src/main/java/com/mtvs/devlinkbackend/config/CorsConfig.java
  src/main/java/com/mtvs/devlinkbackend/config/JwtAuthenticationFilter.java
  src/main/java/com/mtvs/devlinkbackend/config/SecurityConfig.java
  src/main/java/com/mtvs/devlinkbackend/config/SwaggerConfig.java
  src/main/java/com/mtvs/devlinkbackend/config/WebConfig.java
  src/main/java/com/mtvs/devlinkbackend/ether/controller/EtherController.java
  src/main/java/com/mtvs/devlinkbackend/ether/entity/Ether.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/controller/Oauth2UserController.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/dto/EpicGamesCallbackRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/question/controller/QuestionController.java
  src/main/java/com/mtvs/devlinkbackend/reply/controller/ReplyController.java
  src/main/resources/application.yml
Labels: ✨Feature, ✅ Test

#32 [PL-request-crud] 프로젝트 의뢰 CRUD API 구현 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/config/SecurityConfig.java
  src/main/java/com/mtvs/devlinkbackend/ether/controller/EtherController.java
  src/main/java/com/mtvs/devlinkbackend/reply/controller/ReplyController.java
  src/main/java/com/mtvs/devlinkbackend/request/controller/RequestController.java
  src/main/java/com/mtvs/devlinkbackend/request/dto/RequestRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/request/dto/RequestUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/request/entity/Request.java
  src/main/java/com/mtvs/devlinkbackend/request/repository/RequestRepository.java
  src/main/java/com/mtvs/devlinkbackend/request/service/RequestService.java
  src/test/java/com/mtvs/devlinkbackend/request/RequestCRUDTest.java
Labels: ✨Feature, ✅ Test

#35 [PL-team-crud] 프로젝트 팀 CRUD API 구현 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/team/controller/TeamController.java
  src/main/java/com/mtvs/devlinkbackend/team/dto/TeamRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/team/dto/TeamUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/team/entity/Team.java
  src/main/java/com/mtvs/devlinkbackend/team/repository/TeamRepository.java
  src/main/java/com/mtvs/devlinkbackend/team/service/TeamService.java
  src/test/java/com/mtvs/devlinkbackend/team/TeamCRUDTest.java
Labels: ✨Feature, ✅ Test

#36 [PL-guild-crud] 길드 CRUD API 구현 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/guild/controller/GuildController.java
  src/main/java/com/mtvs/devlinkbackend/guild/dto/GuildMemberModifyRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/guild/dto/GuildRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/guild/dto/GuildUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/guild/entity/Guild.java
  src/main/java/com/mtvs/devlinkbackend/guild/repository/GuildRepository.java
  src/main/java/com/mtvs/devlinkbackend/guild/service/GuildService.java
  src/main/java/com/mtvs/devlinkbackend/team/dto/TeamMemberModifyRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/team/entity/Team.java
  src/main/java/com/mtvs/devlinkbackend/team/service/TeamService.java
  src/test/java/com/mtvs/devlinkbackend/crud/CommentCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/EtherCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/GuildCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/QuestionCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/ReplyCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/RequestCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/TeamCRUDTest.java
Labels: ✨Feature, ✅ Test

#37 [PL-channel-crud]
  build.gradle
  src/main/java/com/mtvs/devlinkbackend/DevlinkBackendApplication.java
  src/main/java/com/mtvs/devlinkbackend/channel/controller/ChannelController.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/ChannelRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/dto/ChannelUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/channel/entity/Channel.java
  src/main/java/com/mtvs/devlinkbackend/channel/entity/PositionType.java
  src/main/java/com/mtvs/devlinkbackend/channel/repository/ChannelRepository.java
  src/main/java/com/mtvs/devlinkbackend/channel/service/ChannelService.java
  src/main/java/com/mtvs/devlinkbackend/comment/controller/CommentController.java
  src/main/java/com/mtvs/devlinkbackend/config/JwtAuthenticationFilter.java
  src/main/java/com/mtvs/devlinkbackend/config/JwtUtil.java
  src/main/java/com/mtvs/devlinkbackend/ether/controller/EtherController.java
  src/main/java/com/mtvs/devlinkbackend/guild/controller/GuildController.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/controller/Oauth2UserController.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/service/EpicGamesTokenService.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/service/UserService.java
  src/main/java/com/mtvs/devlinkbackend/question/controller/QuestionController.java
  src/main/java/com/mtvs/devlinkbackend/reply/controller/ReplyController.java
  src/main/java/com/mtvs/devlinkbackend/request/controller/RequestController.java
  src/main/java/com/mtvs/devlinkbackend/team/controller/TeamController.java
  src/main/resources/application.yml
  src/test/java/com/mtvs/devlinkbackend/crud/ChannelCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/TeamCRUDTest.java
Labels: ✨Feature, ✅ Test

#39 [PL-user-crud]
  src/main/java/com/mtvs/devlinkbackend/channel/controller/ChannelController.java
  src/main/java/com/mtvs/devlinkbackend/comment/controller/CommentController.java
  src/main/java/com/mtvs/devlinkbackend/config/JwtAuthenticationFilter.java
  src/main/java/com/mtvs/devlinkbackend/config/SecurityConfig.java
  src/main/java/com/mtvs/devlinkbackend/ether/controller/EtherController.java
  src/main/java/com/mtvs/devlinkbackend/guild/controller/GuildController.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/controller/Oauth2UserController.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/controller/UserClientGroupController.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/controller/UserClientIndividualController.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/controller/UserPartnerController.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/dto/UserClientGroupRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/dto/UserClientIndividualRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/dto/UserPartnerRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/dto/UserRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/dto/UserUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/entity/User.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/entity/UserClientGroup.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/entity/UserClientIndividual.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/entity/UserPartner.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/repository/UserClientGroupRepository.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/repository/UserClientIndividualRepository.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/repository/UserPartnersRepository.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/repository/UserRepository.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/service/EpicGamesTokenService.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/service/UserClientGroupService.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/service/UserClientIndividualService.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/service/UserPartnerService.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/service/UserService.java
  src/main/java/com/mtvs/devlinkbackend/question/controller/QuestionController.java
  src/main/java/com/mtvs/devlinkbackend/reply/controller/ReplyController.java
  src/main/java/com/mtvs/devlinkbackend/request/controller/RequestController.java
  src/main/java/com/mtvs/devlinkbackend/team/controller/TeamController.java
  src/main/java/com/mtvs/devlinkbackend/util/JwtUtil.java
  src/main/java/com/mtvs/devlinkbackend/util/StringListConverter.java
  src/test/java/com/mtvs/devlinkbackend/crud/CommentCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/UserClientGroupCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/UserClientIndividualCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/UserPartnerCRUDTest.java
Labels: ✨Feature, ✅ Test

#40 [PL-character-crud] 캐릭터 CRUD API 구현 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/character/controller/UserCharacterController.java
  src/main/java/com/mtvs/devlinkbackend/character/dto/UserCharacterRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/dto/UserCharacterUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/character/entity/UserCharacter.java
  src/main/java/com/mtvs/devlinkbackend/character/repository/UserCharacterRepository.java
  src/main/java/com/mtvs/devlinkbackend/character/service/UserCharacterService.java
  src/test/java/com/mtvs/devlinkbackend/crud/UserCharacterCRUDTest.java
Labels: ✨Feature, ✅ Test

#42 [DS-refactor-request-header] swagger에 authorize 설정 추가
  src/main/java/com/mtvs/devlinkbackend/config/SwaggerConfig.java
Labels: 🐞Fix, 🔨 Refactor

#47 Fix: jwtAuth 과정 중 검증 로직 수정
  src/main/java/com/mtvs/devlinkbackend/config/JwtAuthenticationFilter.java
  src/main/java/com/mtvs/devlinkbackend/util/JwtUtil.java
Labels: 🐞Fix

#50 DS-refactor-table: 화면 UI에 따른 프로젝트 의뢰 테이블 수정
  src/main/java/com/mtvs/devlinkbackend/request/controller/RequestController.java
  src/main/java/com/mtvs/devlinkbackend/request/dto/RequestRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/request/dto/RequestUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/request/entity/Request.java
  src/main/java/com/mtvs/devlinkbackend/request/repository/RequestRepository.java
  src/main/java/com/mtvs/devlinkbackend/request/service/RequestService.java
  src/test/java/com/mtvs/devlinkbackend/crud/RequestCRUDTest.java
Labels: 🔨 Refactor, ✅ Test

#52 refactor: 도메인 네임 변경 request -> project
  src/main/java/com/mtvs/devlinkbackend/comment/controller/CommentController.java
  src/main/java/com/mtvs/devlinkbackend/comment/entity/Comment.java
  src/main/java/com/mtvs/devlinkbackend/comment/repository/CommentRepository.java
  src/main/java/com/mtvs/devlinkbackend/comment/service/CommentService.java
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectController.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/ProjectRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/ProjectUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/entity/Project.java
  src/main/java/com/mtvs/devlinkbackend/project/repository/ProjectRepository.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectService.java
  src/main/java/com/mtvs/devlinkbackend/request/controller/RequestController.java
  src/main/java/com/mtvs/devlinkbackend/request/service/RequestService.java
  src/test/java/com/mtvs/devlinkbackend/config/CorsProjectTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/CommentCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/ProjectCRUDTest.java
Labels: 🔨 Refactor

#53 refactor: 도메인 네임 변경 request -> project
  src/main/java/com/mtvs/devlinkbackend/project/entity/Project.java
Labels: 🐞Fix

#54 refactor: 도메인 네임 변경 request -> project
  src/main/java/com/mtvs/devlinkbackend/project/repository/ProjectRepository.java
Labels: 🐞Fix

#56 PL-support-crud: 프로젝트 지원 CRUD API 구현 및 TestCode 작성
  src/main/java/com/mtvs/devlinkbackend/character/service/UserCharacterService.java
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectController.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectService.java
  src/main/java/com/mtvs/devlinkbackend/support/controller/SupportController.java
  src/main/java/com/mtvs/devlinkbackend/support/dto/SupportRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/support/entity/Support.java
  src/main/java/com/mtvs/devlinkbackend/support/repository/SupportRepository.java
  src/main/java/com/mtvs/devlinkbackend/support/service/SupportService.java
  src/test/java/com/mtvs/devlinkbackend/crud/ProjectCRUDTest.java
  src/test/java/com/mtvs/devlinkbackend/crud/SupportCRUDTest.java
Labels: ✨Feature, ✅ Test

#58 DS-add-column-vector: Project 도메인에 Vector 정보 추가 및 API 구현
  src/main/java/com/mtvs/devlinkbackend/oauth2/entity/UserPartner.java
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectController.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/ProjectVectorRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/entity/Project.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectService.java
Labels: ✨Feature

#62 DS-add-get-method: 프로젝트 도메인의 조회 메서드 추가 구현
  src/main/java/com/mtvs/devlinkbackend/comment/repository/CommentRepository.java
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectSummaryController.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/response/ProjectDetailResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/response/ProjectSummaryResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/repository/ProjectRepository.java
  src/main/java/com/mtvs/devlinkbackend/project/repository/projection/ProjectIdAndContent.java
  src/main/java/com/mtvs/devlinkbackend/project/repository/projection/ProjectSummary.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectDetailService.java
  src/main/java/com/mtvs/devlinkbackend/support/repository/SupportRepository.java
Labels: ✨Feature

#65 DS-refactor-entity-type-conversion: Project LocalDate Type 변경
  src/main/java/com/mtvs/devlinkbackend/oauth2/dto/request/UserPartnerRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/entity/UserPartner.java
  src/main/java/com/mtvs/devlinkbackend/oauth2/service/UserPartnerService.java
  src/test/java/com/mtvs/devlinkbackend/crud/UserPartnerCRUDTest.java
Labels: 🔨 Refactor

#66 DS-refactor-entity-add-column: UserPartner Entity GithubLink Column 추가
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectController.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/request/ProjectRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/request/ProjectUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/entity/Project.java
  src/main/java/com/mtvs/devlinkbackend/project/repository/ProjectRepository.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectService.java
  src/test/java/com/mtvs/devlinkbackend/crud/ProjectCRUDTest.java
Labels: 🔨 Refactor

#67 fix: Project Summary의 타입 불일치
  src/main/java/com/mtvs/devlinkbackend/project/repository/projection/ProjectSummary.java
Labels: 🐞Fix

#70 69 ds update entity column
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectController.java
  src/main/java/com/mtvs/devlinkbackend/project/controller/ProjectSummaryController.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/request/ProjectRegistRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/request/ProjectUpdateRequestDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/response/ProjectPreviewDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/dto/response/ProjectSummaryPagingResponseDTO.java
  src/main/java/com/mtvs/devlinkbackend/project/entity/Project.java
  src/main/java/com/mtvs/devlinkbackend/project/repository/ProjectRepository.java
  src/main/java/com/mtvs/devlinkbackend/project/repository/projection/ProjectSummary.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectDetailService.java
  src/main/java/com/mtvs/devlinkbackend/project/service/ProjectService.java
  src/main/java/com/mtvs/devlinkbackend/team/controller/TeamController.java
Labels: 🐞Fix, 🔨 Refactor
